exports.ALL_RESOURCES = [
  "dashboard",
  "admin",
  "clients",
  "loan release",
  "expense voucher",
  "journal voucher",
  "acknowledgement",
  "release",
  "audit trail",
  "financial statement",
  "trial balance",
  "group of account",
  "chart of account",
  "product",
  "center",
  "bank",
  "weekly savings",
  "business type",
  "business supplier",
  "unbalance entries",
  "login logs",
  "action logs",
  "emergency loan",
  "damayan fund",
  "nature",
  "beginning balance",
];
