exports.ALL_RESOURCES = [
  "client master file",
  "chart of account",
  "bank",
  "business type",
  "center",
  "loans",
  "weekly saving table",
  "supplier",
  "loan release",
  "journal voucher",
  "expense voucher",
  "emergency loan",
  "damayan fund",
  "official receipt",
  "status",
  "nature",
  "group account",
];
